### ISSUE TITLE
Deployed but cannot run workflow and tests webhook from DO app.

### ISSUE THREAD

**Issue by Nicholas-t** [johnkraczek/n8n-ansible-install#1]
Hi John,

I came across your video you posted a week ago, and tried deploying n8n on digital ocean. While it is deployed, i came across an issue that I cant test webhooks and run request on the workflow. Upon seeing the log, I am seeing error message like this.
```
[n8n-app-do] [2022-05-17 19:40:07] ERROR RESPONSE
[n8n-app-do] [2022-05-17 19:40:07] ResponseError: Execution not found
[n8n-app-do] [2022-05-17 19:40:07]     at /workspace/node_modules/n8n/dist/src/Server.js:1510:23
[n8n-app-do] [2022-05-17 19:40:07]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[n8n-app-do] [2022-05-17 19:40:07]     at async /workspace/node_modules/n8n/dist/src/ResponseHelper.js:91:26 {
[n8n-app-do] [2022-05-17 19:40:07]   httpStatusCode: 404
[n8n-app-do] [2022-05-17 19:40:07] }
[n8n-app-do] [2022-05-17 19:40:07] Attempt to read execution was blocked due to insufficient permissions
```
Do you know what could be the issue ? I am guessing its due to the insufficient permissions

Thanks in advance

**Comment by johnkraczek** [comment]
Hey, can we jump on a Zoom call so I can troubleshoot the issue?

**Comment by Nicholas-t** [comment]
With pleasure. I will create an invitation shortly. If you dont mind, I am inviting a friend of mine to the call who is also interested on the topic.
Best,

**Comment by johnkraczek** [comment]
No problem, Lets get it figured out!
