### ISSUE TITLE
How to update N8N with this installation method?

### ISSUE THREAD

**Issue by hunterxx222** [johnkraczek/n8n-ansible-install#3]
Could you please give a brief guideline on how to update N8N? I tried to find the N8N package in my DigitalOcean droplet but cannot find it. A few lines would help!

**Comment by johnkraczek** [comment]
if you used this ansible script, then you can update n8n by ssh-ing into your box using your admin username (not root) and then running 
`npm install -g n8n` 

for additional reference your home user directory will also contain the ecosystem.config.js which is the PM2 environment file.

using that file you can adjust the environment variables listed here
[n8n environment variables](https://docs.n8n.io/hosting/environment-variables/)

`pm2 list ` will list the node instances you have loaded on your system. 

You can use the PM2 commands to stop start or restart your app
```
pm2 start 0
pm2 stop 0
pm2 restart 0 

```

if you check in the hidden folder .n8n you will find the SQLite database and a config file with your generated encryption keys. 

Let me know if that seems to help you navigate around your N8N instance.

**Comment by hunterxx222** [comment]
Thank you much. I'll try it out and let you know

**Comment by hunterxx222** [comment]
It works. Thank you very much
